### PR TITLE
Added Web.config for Microsoft Internet Information Server (IIS) for …

### PR DESCRIPTION
**Pull request by mscherotter**
….jscad and .amf file types.
And added code to enable file saving/downloading on Microsoft Internet Explorer 11 and Microsoft Edge.

### CODE REVIEW

**Comment by z3dev** [comment]
I see that you've taken up the challenge to put a Blockify wrapper around OpenJSCAD.org. Very cool!

However, I'd like to finish off the current release (0.3.1) as there are some nice functional changes and bug fixes in this release. Can the changes in this pull request wait until the next release?

**Comment by mscherotter** [comment]
Sure - How do I separate out the work?

On Mon, Nov 23, 2015 at 5:42 PM, Z3 Development <notifications@github.com>
wrote:

> I see that you've taken up the challenge to put a Blockify wrapper around
> OpenJSCAD.org. Very cool!
>
> However, I'd like to finish off the current release (0.3.1) as there are
> some nice functional changes and bug fixes in this release. Can the changes
> in this pull request wait until the next release?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Spiritdude/OpenJSCAD.org/pull/104#issuecomment-159124731>
> .
>



-- 
Michael S. Scherotter
mscherotter@gmail.com
http://www.charette.com

**Comment by mscherotter** [comment]
The Commits on November 3 and November 5 are the ones that add the
web.config and fix the file saving support for Microsoft Edge and IE.

On Mon, Nov 23, 2015 at 8:01 PM, Michael Scherotter <mscherotter@gmail.com>
wrote:

> Sure - How do I separate out the work?
>
> On Mon, Nov 23, 2015 at 5:42 PM, Z3 Development <notifications@github.com>
> wrote:
>
>> I see that you've taken up the challenge to put a Blockify wrapper around
>> OpenJSCAD.org. Very cool!
>>
>> However, I'd like to finish off the current release (0.3.1) as there are
>> some nice functional changes and bug fixes in this release. Can the changes
>> in this pull request wait until the next release?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Spiritdude/OpenJSCAD.org/pull/104#issuecomment-159124731>
>> .
>>
>
>
>
> --
> Michael S. Scherotter
> mscherotter@gmail.com
> http://www.charette.com
>



-- 
Michael S. Scherotter
mscherotter@gmail.com
http://www.charette.com

**Comment by mscherotter** [comment]
You can see the site here: http://openjscad.azurewebsites.net/


On Mon, Nov 23, 2015 at 8:04 PM, Michael Scherotter <mscherotter@gmail.com>
wrote:

> The Commits on November 3 and November 5 are the ones that add the
> web.config and fix the file saving support for Microsoft Edge and IE.
>
> On Mon, Nov 23, 2015 at 8:01 PM, Michael Scherotter <mscherotter@gmail.com
> > wrote:
>
>> Sure - How do I separate out the work?
>>
>> On Mon, Nov 23, 2015 at 5:42 PM, Z3 Development <notifications@github.com
>> > wrote:
>>
>>> I see that you've taken up the challenge to put a Blockify wrapper
>>> around OpenJSCAD.org. Very cool!
>>>
>>> However, I'd like to finish off the current release (0.3.1) as there are
>>> some nice functional changes and bug fixes in this release. Can the changes
>>> in this pull request wait until the next release?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/Spiritdude/OpenJSCAD.org/pull/104#issuecomment-159124731>
>>> .
>>>
>>
>>
>>
>> --
>> Michael S. Scherotter
>> mscherotter@gmail.com
>> http://www.charette.com
>>
>
>
>
> --
> Michael S. Scherotter
> mscherotter@gmail.com
> http://www.charette.com
>



-- 
Michael S. Scherotter
mscherotter@gmail.com
http://www.charette.com

**Comment by Spiritdude** [comment]
Interesting, Blocky as "overlay", which creates .json - nice idea.

**Comment by z3dev** [comment]
@mscherotter Happy New Year!

I suggest we try to break this into some smaller pieces. Are there some "fixes" for Windows 10? If so then let's start there.

Please don't loose any changes in your local repository. You should be able to make a full copy for backup.

**Comment by mscherotter** [comment]
OK - I am caught up with a few things right now but will start that soon.
Michael

On Wed, Jan 13, 2016 at 12:17 AM, Z3 Development <notifications@github.com>
wrote:

> @mscherotter <https://github.com/mscherotter> Happy New Year!
>
> I suggest we try to break this into some smaller pieces. Are there some
> "fixes" for Windows 10? If so then let's start there.
>
> Please don't loose any changes in your local repository. You should be
> able to make a full copy for backup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Spiritdude/OpenJSCAD.org/pull/104#issuecomment-171212777>
> .
>



-- 
Michael S. Scherotter
mscherotter@gmail.com
http://www.charette.com

**Comment by z3dev** [comment]
I think that the best way forward would be...

Close this pull request (and #102)
Save the old local repository
Make a new local repository & sync with DEV (let me know if you need help here)
Make changes for Windows 10 & test (run all the examples at least)
Push the changes back to your forked version of OpenJSCAD.org
Make a new pull request for the Windows 10 changes

Sorry about all this extra work.

**Comment by z3dev** [comment]
@mscherotter Please try again. There are too many changes to determine what is important versus what is a new library.

Please split this pull request into pieces, which can be reviewed independently.

We would love to have support for Explorer and Edge.
We would love to see Blockify based webpages.

**Pull request closed without merging**
