### PR TITLE
added color parameter type

### PR DESCRIPTION
**Pull request by cmchap**
Added the ability to include a parameter that lets the user choose a color via their operating system's built-in color picker. 

I'm new to javascript and have never meaningfully contributed to OSS, so please review to be sure it matches any style/standards in the rest of the repo.

### CODE REVIEW

**Comment by z3dev** [comment]
@cmchap Thanks for the changes. The code looks fine. Welcome to the world of JavaScript programming.

FYI, we have been working on some changes to add all HTML5 input types to the available parameter types, including color, range (sliders), dates, etc. These will be available very shortly in the Alpha 0.3.1 Release. Please try the new release once it becomes available.

**Comment by z3dev** [comment]
@cmchap thanks again for the enhancements
OpenJSCAD.org Version 0.3.1 has been committed. This release as support for the HTLM5 color chooser. There's a new example called "Balloons" that shows how to use most of the new parameter types.
Does the new color chooser supply what you're looking for?

**Comment by cmchap** [comment]
The new color chooser does exactly what I wanted. Thanks!

**Comment by z3dev** [comment]
@cmchap thanks
I'm closing this pull request.
Please continue to submit changes and ideas.

**Pull request closed without merging**
