### PR TITLE
Retain customized parameter values on rebuildSolid

### PR DESCRIPTION
**Pull request by apla**

### CODE REVIEW

**Comment by kaosat-dev** [comment]
Hi @apla  thanks for the PR ! I just tried it locally , and I am running into an issue : every time I modify a parameter's default value after a first rebuild , I get a "ReferenceError: valueIndex is not defined" error .

**Comment by apla** [comment]
I've backported changeset from my own fork, so maybe something isn't correct. I'll try to build `dev` branch tomorrow and fix this issue

**Comment by kaosat-dev** [comment]
any news on this @apla  ? perhaps I can help if something is amiss ?

**Comment by apla** [comment]
Actually I've found an issue, directly tied to this one. When error occured, parameters resetting to default. Working on fix.

How do you tested my pull request?

**Comment by kaosat-dev** [comment]
@apla  cool !
For testing , I pretty much follow this : https://help.github.com/articles/checking-out-pull-requests-locally/
(mainly fetching & pulling your PR branch onto a local copy)

**Comment by apla** [comment]
I'm fine with push/pull and merge.

As I understand, you're using rollup to build js packages. There is a two rollup configurations — cli and module. Additionally, there is a some npm scripts. What procedure (or script sequence) you're using to build, lift and test pull request locally?

**Comment by apla** [comment]
Found the error, just typo.

Last three commits is for situation when the error is introduced.

**Comment by kaosat-dev** [comment]
Hi @apla ! Sorry it took me so long, but I tested your updates and it works great now! Thanks !
Also code seems good as well.
@z3dev , can we please merge this one :)

**Pull request merged**
