### PR TITLE
Fix for Issue #51 case-sensitive file extensions

### PR DESCRIPTION
**Pull request by thehans**

### CODE REVIEW

**Comment by z3dev** [comment]
This looks fine.

**Comment by thehans** [comment]
Yes, this has completely turned me off of trying to conrtibute anything to this project when a straightforward one line bug fix is ignored for months.

**Comment by z3dev** [comment]
@thehans sorry about that. we have been working with the authors of CSG.js to merge in a fairly large set of changes. we hope to make more rapid changes going forward. please continue to contribute.

**Comment by Spiritdude** [comment]
@thehans I like your contributions, and yes, I have been slow with including PRs. I tried to address this by contacting active developers incl. you "OpenJSCAD Chat Meeting", but the response was underwhelming, and you were mute entirely. So, that your frustration is your right, but when it was about to find a solution you were absent. @z3dev I'm back online sort of but not very steady, I try catch up and make dev to master - I wish more people would give feedback of current dev, but I realize this needs some structure to organize etc . . .

**Pull request merged**
