### PR TITLE
stop color interpolation with smooth lighting on

### PR DESCRIPTION
**Pull request by makc**
Ah what a hell. The color spill bug fix referenced in #137

### CODE REVIEW

**Comment by makc** [comment]
That's what I did, but perhaps proper solution would be to compare polygon.shared

**Comment by z3dev** [comment]
@makc thanks
The smoothing of rendered objects is interesting.
I tried the changes and viewed some of the examples. Some turned out very nice, like the Spring example. While others turned out a little strange, like edges on cubes or flat faces.
It seems to me that smoothing could be beneficial for different applications, i.e. those with different requirements for viewing objects. Why are you using smoothing?
Although not perfect, I think that the changes improve this little know feature.

**Comment by makc** [comment]
> While others turned out a little strange, like edges on cubes or flat faces

this PR only fixes colors leaking into unrelated faces. in order for the cube to look as expected, its faces need to have different colors (I used colors that differ by 1e-4 so that actual color looks the same).

**Comment by makc** [comment]
> Why are you using smoothing?

I do not actually use smoothing, I used matcap materials:

screen shot 2016-02-25 at 14 09 46
screen shot 2016-02-25 at 17 27 59
screen shot 2016-02-25 at 17 43 07
screen shot 2016-02-25 at 17 43 33

but this is the client request, they were not happy with flat look it had.

**Comment by z3dev** [comment]
Thanks for all this very useful information.

How did you incorporate the matcap lighting into the openjscad.js library? That would be a very interesting addition to OpenJSCAD.org. You could introduce this to the OpenJSCAD.org community, and see if anyone has interest.

I do!

Making OpenJSCAD.org more useful and flexible to others is a major goal of mine.

**Comment by makc** [comment]
once you have smoothing shading fixed, you can swap the shader to whatever you want... including matcap ) you can find reference implementation [here](https://www.clicktorelease.com/blog/creating-spherical-environment-mapping-shader), although it is somewhat broken, too, if you look at the edges, for example, and relies on undefined behavior of pow.

**Comment by z3dev** [comment]
I'm closing this pull request as the changes have been incorporated and tested in the 0.5.1

Thanks again!

**Pull request closed without merging**
