### PR TITLE
Enhanced the editor frame to slide in and out by clicking a tab

### PR DESCRIPTION
**Pull request by z3dev**
This is a nice enhancement, allowing the editor frame to slide in and out. There's a new tab which can be clicked to control the view.

This addresses #79 by @thehans 

I've been using this for some time at www.z3d.jp/lab/

### CODE REVIEW

**Comment by Spiritdude** [comment]
Nice feature, but it would be better to actually drag it ... to narrow and make it wider.

**Comment by Spiritdude** [comment]
The left-hand handlers works different, hovering is enough (self explanatory, does not need click, it acts right away, and the behaviour is introduce at loading of the page). Alike the right handler should be, self-explanatory.

**Comment by Spiritdude** [comment]
Btw, the handle you can adapt as defined in imgs/misc.svg, I designed left-right, right-left, top-down, down-top versions, best use Inkscape to add it to imgs/misc.svg

**Comment by Spiritdude** [comment]
I provide suitable handle for in/out switch.

**Comment by Spiritdude** [comment]
I just added it, proper handle and transitional animation.

**Comment by z3dev** [comment]
@Spiritdude 
Cool. I'll use Inkscape to create ew graphics next time.
However, the individual PNG files are missing. Can you provide?

**Pull request merged**
