### PR TITLE
Modeling tests & superficial code cleanup

### PR DESCRIPTION
**Pull request by kaosat-dev**
Ready for MERGE !
This PR adds unit tests for all the functional modeling helpers, so that we have a good , tested baseline to expand things from.

- [x] 2d primitives
- [x] 3d primitives
- [x] extrusion ops
- [x] boolean ops
- [x] transformation ops
- [x] colors 
- [x] maths 
- [x] text 

To run all the test (including the already passing ones for the CLI & module) type `npm test`
or `npm t`

Non passing tests are there for a reason:
- unexpected behaviour 
- weird api issues 
- this PR is not meant to fix issues, just to add the tests highlighting them :)
unless I got something really wrong :)

### CODE REVIEW

**Comment by kaosat-dev** [comment]
@z3dev  just some minor cleanups, not changing anything about the way the parameters are actually handled

**Comment by dav-m85** [comment]
In my mind, CSG was a entirely different library, it is weird to have tests here instead of in https://evanw.github.io/csg.js/ where the csg file is originaly coming from. What about putting these tests in a PR to the source repository ?

**Comment by kaosat-dev** [comment]
@dav-m85 these are not tests for the CSG.js module/lib : these are specifically for the 'openscad style' functional wrappers/tools :)

**Comment by dav-m85** [comment]
Oops so sorry, I was reading this code too fast I guess :)

**Comment by kaosat-dev** [comment]
@dav-m85  no worries :)
Btw , perhaps not the best place to discuss it, but we need to find a new home for an updated cgs.js since the original is not maintained any more, so we will be moving /creating some repositories in a Github organization soonish so that it can be more community maintained (ping @z3dev )

**Comment by dav-m85** [comment]
There's already [https://github.com/csg-js](https://github.com/csg-js), created by @bhouston in this thread: https://github.com/evanw/csg.js/issues/13. He was even offering writing tests.

There's also the npm package https://www.npmjs.com/package/csg pointing to a fork, already used as a dependency in a few other packages. No luck either for the moment https://github.com/evanw/csg.js/issues/18

I think these two places could be a good starting point to merge all the csg copies across all projects...

**Comment by kaosat-dev** [comment]
@dav-m85 perhaps we can open a discussion for the points above , we are going off track for this PR , which is done as far as I am concerned :)

**Comment by dav-m85** [comment]
@kaosat-dev absolutely. Shall we start a gitter ?

**Comment by dav-m85** [comment]
Gitter started: https://gitter.im/OpenJSCAD-org/Lobby

**Comment by z3dev** [comment]
FYI, I have started a set of tests for CSG and CAG, but haven't decided on WHERE this should live. If we come to a conclusion on where then I'd be glad to post what I have.

**Comment by dav-m85** [comment]
Oh that's great @z3dev. Could you open a PR to https://github.com/jscad/csg.js ? I already have a few very naive tests WIP https://github.com/jscad/csg.js/pull/2, maybe our works are complementary :)

**Comment by z3dev** [comment]
If not then i'll adjust. But I won't have time until this weekend. Cheers

**Comment by bhouston** [comment]
I support moving this to the https://github.com/jscad ORganization, especially if I am a member.  We use this stuff at Clara.io but it isn't very stable at all.

**Comment by kaosat-dev** [comment]
@bhouston I will gladly add you as a member ! By 'moving this' : what is the **this** refering to ? The csg.js library , the openjscad one ?

**Comment by bhouston** [comment]
I thought someone was trying to centralize this under the jscad project.  I may have been wrong.  Sorry.  Sort of came into this discussion late.  But it would be cool to see this stuff working well if that was possible.  I'm not a CAD kernel expert myself, more of a glsl/shader and polygon geometry guy -- e.g. Clara.io stuff.

**Comment by kaosat-dev** [comment]
@bhouston  no actually you are completely right, the idea is to move all related projects (csg.js, openjscad, openscad-openjscad translator to a single org, the one you pointed to)
The discussion was/is here : 
https://github.com/Spiritdude/OpenJSCAD.org/issues/213

I added you to the Org btw :)

**Pull request merged**
